// ── FIX MY MENU ─────────────────────────────────────────────────────────────
// Single button that scaffolds and rebalances the 14-day menu.
// Slice 2 (this file): cleanup pass + planning window + placeholder generator
//                      + button wiring. NO service assignment yet (that's Slice 3).
// See .claude/plans/fix-my-menu.md for the full spec.

import type { Batch, DishType, Location, Meal } from '@shared/types';
import { S } from './state';
import { newId, scheduleSave, toast } from './utils';
import { rebuildPlanner, getToday, dateToIso, dateToStr, dateToDayName, isServicePast } from './core';
import { rerenderCurrentView } from './navigate';

// ── Constants ───────────────────────────────────────────────────────────────

// Weekly cook rhythm. All cooking happens at West by default.
// Sunday is the big-cook day (lots of volunteers); Mon/Tue live off Sunday's
// surplus so cooks can clean and organise. Wed–Sat are steady 1+1 days.
export const COOK_RHYTHM: Record<string, { soup: number; main: number }> = {
  Sun: { soup: 3, main: 3 },
  Mon: { soup: 0, main: 1 },
  Tue: { soup: 1, main: 0 },
  Wed: { soup: 1, main: 1 },
  Thu: { soup: 1, main: 1 },
  Fri: { soup: 1, main: 1 },
  Sat: { soup: 1, main: 1 },
};

export const SLOTS_PER_TYPE = 2;
export const PLANNING_HORIZON_DAYS = 14;
export const STALE_THRESHOLD_DAYS = 3;
export const TYPES_TO_PLAN: DishType[] = ['Soup', 'Main course'];

// All four service slots per day, in the canonical order Pass 2 will use later
// (Centraal before West so Centraal slots get filled first when the algorithm
// has to choose between them — see spec §3.3 Step 4).
const SERVICE_SLOTS_PER_DAY: { loc: Location; meal: Meal }[] = [
  { loc: 'centraal', meal: 'lunch' },
  { loc: 'centraal', meal: 'dinner' },
  { loc: 'west', meal: 'lunch' },
  { loc: 'west', meal: 'dinner' },
];

// ── Types ───────────────────────────────────────────────────────────────────

export interface PlanSlot {
  loc: Location;
  meal: Meal;
  isPast: boolean;
}

export interface PlanDay {
  date: Date;
  isoDate: string;       // "YYYY-MM-DD"  — for Service.date
  cookDateStr: string;   // "DD/MM/YYYY"  — for Batch.cookDate
  dayName: string;       // 'Mon' | 'Tue' | ...
  slots: PlanSlot[];
}

export interface BatchSnapshot {
  cookEventsByCookDate: Map<string, { Soup: Batch[]; 'Main course': Batch[] }>;
  // Reserved for Slice 3: cooked vs uncooked, catering reservations, etc.
  inWindow: Batch[];
}

export interface FixReport {
  createdPlaceholders: Batch[];
  cleanedOrphans: number;
}

// ── Step 1: Build planning window ───────────────────────────────────────────

export function buildPlanningWindow(today: Date, horizonDays = PLANNING_HORIZON_DAYS): PlanDay[] {
  const days: PlanDay[] = [];
  for (let i = 0; i < horizonDays; i++) {
    const d = new Date(today.getFullYear(), today.getMonth(), today.getDate() + i);
    const isoDate = dateToIso(d);
    const slots: PlanSlot[] = SERVICE_SLOTS_PER_DAY.map(s => ({
      loc: s.loc,
      meal: s.meal,
      isPast: isServicePast({ loc: s.loc, date: isoDate, meal: s.meal }),
    }));
    days.push({
      date: d,
      isoDate,
      cookDateStr: dateToStr(d),
      dayName: dateToDayName(isoDate),
      slots,
    });
  }
  return days;
}

// ── Step 2: Snapshot existing state ─────────────────────────────────────────

export function snapshotBatches(batches: Batch[], window: PlanDay[]): BatchSnapshot {
  const cookEventsByCookDate = new Map<string, { Soup: Batch[]; 'Main course': Batch[] }>();
  for (const day of window) {
    cookEventsByCookDate.set(day.cookDateStr, { Soup: [], 'Main course': [] });
  }

  const inWindow: Batch[] = [];
  for (const b of batches) {
    if (!TYPES_TO_PLAN.includes(b.type)) continue;            // skip Desserts entirely
    if (!b.cookDate) continue;                                // unscheduled, ignore
    const bucket = cookEventsByCookDate.get(b.cookDate);
    if (!bucket) continue;                                    // outside window
    bucket[b.type as 'Soup' | 'Main course'].push(b);
    inWindow.push(b);
  }

  return { cookEventsByCookDate, inWindow };
}

// ── Step 0: Cleanup orphan generated placeholders ───────────────────────────

/**
 * Returns the batches that should be deleted because they were generated by a
 * previous run, never got assigned to a service, and were never linked to a
 * recipe. This makes the algorithm idempotent — pressing the button twice in a
 * row produces the same result, because the second run undoes the placeholders
 * the first run created (and then recreates them from scratch).
 *
 * Cook-created placeholders (`generated !== true`) are NEVER returned here.
 */
export function findOrphanPlaceholders(batches: Batch[]): Batch[] {
  return batches.filter(b =>
    b.generated === true
    && (!b.services || b.services.length === 0)
    && !b.recipeId
    && !b.recipeSheetId
  );
}

// ── Step 3: Generate missing placeholders ───────────────────────────────────

interface PlaceholderInput {
  cookDateStr: string;
  isoDate: string;
  dayName: string;
  type: DishType;
  index: number;     // 1-based among same-day same-type
  total: number;     // total of this type cooked this day per rhythm
}

/**
 * Build a fully-typed Batch placeholder. Defaults to West for cooking, no
 * services attached (Slice 3 fills those). Sets `generated: true` so future
 * cleanup passes know it's safe to remove if unused.
 */
function buildPlaceholder(input: PlaceholderInput): Batch {
  const typeLabel = input.type === 'Main course' ? 'Main' : 'Soup';
  const name = input.total > 1
    ? `${input.dayName} ${typeLabel} ${input.index}`
    : `${input.dayName} ${typeLabel}`;

  return {
    id: newId(),
    name,
    type: input.type,
    stock: 0,
    serving: 280,
    storage: 'Gastro',
    location: 'west',
    inTransit: false,
    allergens: [],
    extraAllergens: [],
    orderFor: false,
    parentId: null,
    cookDate: input.cookDateStr,
    recipeSheetId: null,
    recipeVolume: null,
    recipeIngredients: null,
    note: '',
    services: [],
    createdAt: new Date().toISOString(),
    recipeId: null,
    actualIngredients: null,
    cookNotes: '',
    stockDeducted: false,
    generated: true,
  };
}

/**
 * For each day in the window and each type-to-plan, count how many uncooked
 * batches already exist on that day vs. what the rhythm wants, and emit
 * placeholder Batches to fill the gap.
 *
 * If a day already has more cook events than the rhythm prescribes (e.g. a
 * cook decided to make 2 soups on a Wednesday), we leave the extras alone —
 * never delete or "normalize down".
 */
export function generateMissingPlaceholders(window: PlanDay[], snapshot: BatchSnapshot): Batch[] {
  const newBatches: Batch[] = [];

  for (const day of window) {
    const rhythm = COOK_RHYTHM[day.dayName];
    if (!rhythm) continue;
    const bucket = snapshot.cookEventsByCookDate.get(day.cookDateStr);
    if (!bucket) continue;

    for (const type of TYPES_TO_PLAN) {
      const target = type === 'Soup' ? rhythm.soup : rhythm.main;
      const existing = bucket[type as 'Soup' | 'Main course'].length;
      const gap = target - existing;
      if (gap <= 0) continue;

      for (let i = 0; i < gap; i++) {
        newBatches.push(buildPlaceholder({
          cookDateStr: day.cookDateStr,
          isoDate: day.isoDate,
          dayName: day.dayName,
          type,
          index: existing + i + 1,
          total: target,
        }));
      }
    }
  }

  return newBatches;
}

// ── Entry point ─────────────────────────────────────────────────────────────

/**
 * Slice 2 entry point: cleanup → window → snapshot → placeholders → save.
 * Service assignment (Pass 1, Pass 2) and the validation/rescue UI come in
 * later slices.
 */
export function fixMyMenu(): void {
  const ok = window.confirm(
    "Fix my menu will fill empty cook days with placeholder batches and clean up unused placeholders from previous runs.\n\n" +
    "Existing batches won't be removed or renamed.\n\n" +
    "Continue?"
  );
  if (!ok) return;

  // Step 0: cleanup orphan placeholders from previous runs
  const orphans = findOrphanPlaceholders(S.batches);
  if (orphans.length > 0) {
    const orphanIds = new Set(orphans.map(b => b.id));
    S.batches = S.batches.filter(b => !orphanIds.has(b.id));
    if (!S.deletedBatches) S.deletedBatches = [];
    for (const id of orphanIds) S.deletedBatches.push(id);
  }

  // Step 1: build the 14-day planning window
  const planWindow = buildPlanningWindow(getToday());

  // Step 2: snapshot existing batches keyed by cookDate
  const snapshot = snapshotBatches(S.batches, planWindow);

  // Step 3: generate placeholders for missing cook events
  const newPlaceholders = generateMissingPlaceholders(planWindow, snapshot);
  for (const b of newPlaceholders) {
    S.batches.push(b);
  }

  // Persist + refresh
  rebuildPlanner();
  rerenderCurrentView();
  scheduleSave();

  // Slice 2 result UI: simple toast. Slice 4 replaces this with a results
  // modal that includes service-fill summary, warnings, and rescue actions.
  const cleaned = orphans.length;
  const created = newPlaceholders.length;
  if (created === 0 && cleaned === 0) {
    toast('Menu already covers the cook rhythm — nothing to add.');
  } else {
    const parts: string[] = [];
    if (created > 0) parts.push(`Created ${created} placeholder${created === 1 ? '' : 's'}`);
    if (cleaned > 0) parts.push(`cleaned ${cleaned} unused`);
    toast(parts.join(', '));
  }
}
